version: "3.9"

services:
  db:
    image: postgres:14
    container_name: ixi-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ixi_keeper
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ixi_keeper"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ixi-server
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ixi_keeper
      DB_HOST: db
      DB_PORT: 5432
      DB_DIALECT: postgres
      NODE_ENV: development
      PORT: 3020
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3020:3020"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ixi-client
    environment:
      NODE_ENV: development
    depends_on:
      - server
    ports:
      - "3021:3021"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  dbdata:
